{"timestamp":"2025-08-21T07:56:55.213302","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T07:56:55.213896","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T07:56:55.276280Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:55.276779Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:55.277384Z","level":"info","event":"Current task name:clean_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:55.277679Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.447853Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.448190Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 165, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.450041Z","level":"error","event":"    data_cleaning()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.450409Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 126, in data_cleaning","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.451882Z","level":"error","event":"    pollutants_fact_new = df_merged[pollution_cols + df_merged[['weather_id','city']]].drop_duplicates().reset_index(drop=True)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.452167Z","level":"error","event":"                                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.452402Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py\", line 76, in new_method","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.453869Z","level":"error","event":"    return method(self, other)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.454262Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.454520Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py\", line 190, in __radd__","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.454907Z","level":"error","event":"    return self._arith_method(other, roperator.radd)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.455224Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.455505Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 7641, in _arith_method","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.456727Z","level":"error","event":"    self, other = self._align_for_op(other, axis, flex=True, level=None)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.457089Z","level":"error","event":"                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.457366Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 7918, in _align_for_op","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.457856Z","level":"error","event":"    right = to_series(right)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.458089Z","level":"error","event":"            ^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.458406Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 7864, in to_series","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.459051Z","level":"error","event":"    raise ValueError(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.459355Z","level":"error","event":"ValueError: Unable to coerce to Series, length must be 2: given 9","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.553650","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":16,"name":"clean_data"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T07:56:56.555170Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.555622Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.555900Z","level":"info","event":"Task:<Task(PythonOperator): clean_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:56:56.559579Z","level":"info","event":"Failure caused by Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
