{"timestamp":"2025-08-21T07:50:27.400083","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T07:50:27.400631","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T07:50:27.455411Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:27.456026Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:27.458108Z","level":"info","event":"Current task name:clean_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:27.458421Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.435574Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.435953Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 266, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.437882Z","level":"error","event":"    data_cleaning()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.438176Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 258, in data_cleaning","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.439955Z","level":"error","event":"    create_pollutants_fact(df_merged, date_dim, location_dim, weather_dim)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.440260Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 164, in create_pollutants_fact","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.441761Z","level":"error","event":"    pollutants_fact_new = df_merged[[","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.441993Z","level":"error","event":"                          ^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.442216Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 3899, in __getitem__","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.447022Z","level":"error","event":"    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.447498Z","level":"error","event":"              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.447767Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py\", line 6115, in _get_indexer_strict","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.452089Z","level":"error","event":"    self._raise_if_missing(keyarr, indexer, axis_name)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.452396Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py\", line 6179, in _raise_if_missing","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.452884Z","level":"error","event":"    raise KeyError(f\"{not_found} not in index\")","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.453417Z","level":"error","event":"KeyError: \"['pollution_co', 'pollution_no', 'pollution_no2', 'pollution_o3', 'pollution_so2', 'pollution_pm2_5', 'pollution_pm10', 'pollution_nh3'] not in index\"","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.543029","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":16,"name":"clean_data"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T07:50:28.544486Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.544822Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.545110Z","level":"info","event":"Task:<Task(PythonOperator): clean_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:50:28.545403Z","level":"info","event":"Failure caused by Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
