{"timestamp":"2025-08-21T08:17:00.168092","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T08:17:00.168694","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T08:17:00.226093Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:00.226670Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:00.227324Z","level":"info","event":"Current task name:clean_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:00.227701Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.484882Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.485284Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 180, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.488632Z","level":"error","event":"    data_cleaning()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.489075Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 155, in data_cleaning","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.490857Z","level":"error","event":"    pollutants_fact = pollutants_fact[cols_for_snowflake]","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.491250Z","level":"error","event":"                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.491547Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 3899, in __getitem__","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.491835Z","level":"error","event":"    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.492098Z","level":"error","event":"              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.492407Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py\", line 6115, in _get_indexer_strict","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.492776Z","level":"error","event":"    self._raise_if_missing(keyarr, indexer, axis_name)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.493104Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py\", line 6179, in _raise_if_missing","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.493438Z","level":"error","event":"    raise KeyError(f\"{not_found} not in index\")","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.493783Z","level":"error","event":"KeyError: \"['components_no2', 'components_pm2_5'] not in index\"","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.603725","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":16,"name":"clean_data"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T08:17:01.605607Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.606017Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.606318Z","level":"info","event":"Task:<Task(PythonOperator): clean_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T08:17:01.606573Z","level":"info","event":"Failure caused by Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
